# Generated by Django 5.1.2 on 2024-10-24 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appraiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=45, unique=True)),
                ('permissions', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='worktime',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='payroll_period',
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_date', models.DateField()),
                ('due_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loanstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('appraised_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateField()),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appraiser')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.appraiser')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loan')),
            ],
        ),
        migrations.AddField(
            model_name='appraiser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.role'),
        ),
        migrations.DeleteModel(
            name='Deduction',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='WorkTime',
        ),
        migrations.DeleteModel(
            name='PayrollPeriod',
        ),
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
